apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyblue-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: skyblue
  template:
    metadata:
      labels:
        app: skyblue
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
